from typing import Protocol, Any, Dict, List, runtime_checkable

@runtime_checkable
class IStream(Protocol):
    """Abstract interface for any communication channel (DIP)"""
    def put(self, item: Any) -> None: ...
    def get(self) -> Any: ...
    def qsize(self) -> int: ...
    def empty(self) -> bool: ...

class IObserver(Protocol):
    """Abstract interface for Telemetry Observers"""
    def update(self, stats: Dict[str, float]) -> None: ...
