from typing import Protocol, Any, Dict, List, runtime_checkable

@runtime_checkable
class IStream(Protocol):
    def put(self, item: Any) -> None: ...
    def get(self) -> Any: ...
    def qsize(self) -> int: ...
    def empty(self) -> bool: ...

class IObserver(Protocol):
    def update(self, stats: Dict[str, float]) -> None: ...

class ISubject(Protocol):
    def attach(self, observer: IObserver) -> None: ...
    def notify(self) -> None: ...
